name: Build RPM
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        releasever: [rawhide, 44, 43, 42]
        arch: [x86_64, aarch64, i386, riscv64]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-22.04-arm' || matrix.arch == 'riscv64' && 'banana-pi-f3' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/terrapkg/builder:f${{ matrix.releasever }}
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Checkout Terra repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: terrapkg/packages
          fetch-depth: 0
      - name: Checkout Mock Configs
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          path: mock-configs

      - name: Set up git repository
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Include custom build template instead of package default
        run: cp -v mock-configs/terra*.tpl /etc/mock/templates/

      - name: Build with Andaman
        run: anda build terra/mock-configs -c mock-configs/terra-${{ matrix.releasever }}-${{ matrix.arch }}.cfg

      - name: Generating artifact name
        id: art
        run: |
          NAME=terra-mock-configs-${{ matrix.arch }}-${{ matrix.releasever }}
          x=${NAME//\//@}
          echo "name=$x" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ steps.art.outputs.name }}
          compression-level: 0 # The RPMs are already compressed :p
          path: |
            anda-build/rpm/rpms/*
            anda-build/rpm/srpm/*

  build-el10:
    strategy:
      matrix:
        arch: [x86_64, aarch64, riscv64]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-22.04-arm' || matrix.arch == 'riscv64' && 'banana-pi-f3' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/terrapkg/builder:el10
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Checkout Terra repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: terrapkg/packages
          fetch-depth: 0
      - name: Checkout Mock Configs
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          path: mock-configs

      - name: Set up git repository
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Include custom build template instead of package default
        run: cp -v mock-configs/*.tpl /etc/mock/templates/

      - name: Build with Andaman
        run: anda build terra/mock-configs -c mock-configs/terra-el10-${{ matrix.arch }}.cfg

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: mock-configs-el10
          compression-level: 0 # The RPMs are already compressed :p
          path: |
            anda-build/rpm/rpms/*
            anda-build/rpm/srpm/*
